name: Build and Push to ECR

on:
  push:
    branches: [main]

env:
  ACCOUNT_ID: "874505351656" # set your aws account id
  REGION: "us-east-1" # set your aws region (e.g., us-east-1)
  REPO_NAME: "cs1660-homework2" # set your ecr repository name

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: login to amazon ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: build, tag, and push to ecr
        run: |
          # Build
          docker build -t cs1660-hw2:v1 .

          # Tag
          docker tag cs1660-hw2:v1 874505351656.dkr.ecr.us-east-1.amazonaws.com/cs1660-homework2:v1

          # Push
          docker push 874505351656.dkr.ecr.us-east-1.amazonaws.com/cs1660-homework2:v1
